package cpu;

import Items.Job;
import Items.Queue;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/*import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.ColumnSpec;
import com.jgoodies.forms.factories.FormFactory;
import com.jgoodies.forms.layout.RowSpec;*/


import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

import java.awt.Dimension;

import javax.swing.JTextField;


import net.miginfocom.swing.MigLayout;

import javax.swing.JButton;

import java.awt.Cursor;
import java.awt.SystemColor;
import java.awt.Color;
import java.awt.Font;

import javax.swing.border.LineBorder;



import java.io.*;
import java.util.*;

/**
 *
 * used to add the jobs data manually
 */
@SuppressWarnings("serial")
public class AddData extends javax.swing.JFrame {
	
    /**
     * Creates new form AddData
     */
    public AddData() {
    	getContentPane().setBackground(SystemColor.inactiveCaptionText);
    	setTitle("JOB DATA");
    	setRootPaneCheckingEnabled(false);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new MigLayout("", "[39.00px][47.00px][47.00px][49.00px][9.00px][157.00]", "[23px][][][23px][23px][23px][23px][23px][23px][23px][][23px][23px][23px]"));
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new Font("Book Antiqua", Font.BOLD, 12));
        jLabel11.setForeground(new Color(0x05c986));
        jLabel11.setBackground(new Color(255, 235, 205));
        
                jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel11.setText("Arrive");
                jLabel11.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel11.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel11.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel11, "cell 1 1,alignx center,aligny center");
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setForeground(new Color(0x05c986));
        jLabel12.setFont(new Font("Book Antiqua", Font.BOLD, 12));
        
                jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel12.setText("Burst");
                jLabel12.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel12.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel12.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel12, "cell 2 1,alignx center,growy");
                        
                        lblPriority = new JLabel("Priority");
                        lblPriority.setForeground(new Color(0x05c986));
                        lblPriority.setFont(new Font("Book Antiqua", Font.BOLD, 12));
                        getContentPane().add(lblPriority, "cell 3 1,alignx center");
                        
                        lblTo = new JLabel("(0 to 30)");
                        lblTo.setForeground(new Color(0x05c986));
                        lblTo.setFont(new Font("Book Antiqua", Font.BOLD, 12));
                        getContentPane().add(lblTo, "cell 1 2,alignx center,aligny center");
                        
                        lblNewLabel = new JLabel("(1 to 13)");
                        lblNewLabel.setForeground(new Color(0x05c986));
                        lblNewLabel.setFont(new Font("Book Antiqua", Font.BOLD, 12));
                        getContentPane().add(lblNewLabel, "cell 2 2,alignx center,aligny center");
                        
                        lblNewLabel_1 = new JLabel("(1 to 127)");
                        lblNewLabel_1.setForeground(new Color(0x05c986));
                        lblNewLabel_1.setFont(new Font("Book Antiqua", Font.BOLD, 12));
                        getContentPane().add(lblNewLabel_1, "cell 3 2,alignx center,aligny center");
                
                        jTextField1 = new javax.swing.JTextField();
                        jTextField1.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                        jTextField1.setForeground(new Color(0x05c986));
                        jTextField1.setBackground(SystemColor.inactiveCaptionText);
                                jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                                jTextField1.setText("0");
                                jTextField1.setMaximumSize(new java.awt.Dimension(40, 20));
                                jTextField1.setMinimumSize(new java.awt.Dimension(40, 20));
                                jTextField1.setPreferredSize(new java.awt.Dimension(40, 20));
                                getContentPane().add(jTextField1, "cell 1 3,alignx center,growy");
                jTextField2 = new javax.swing.JTextField();
                jTextField2.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                jTextField2.setForeground(new Color(0x05c986));
                jTextField2.setBackground(SystemColor.inactiveCaptionText);
                
                        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                        jTextField2.setText("0");
                        jTextField2.setMaximumSize(new java.awt.Dimension(40, 20));
                        jTextField2.setMinimumSize(new java.awt.Dimension(40, 20));
                        jTextField2.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jTextField2, "cell 2 3,alignx center,growy");
                jTextField3 = new javax.swing.JTextField();
                jTextField3.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                jTextField3.setForeground(new Color(0x05c986));
                jTextField3.setBackground(SystemColor.inactiveCaptionText);
                
                        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                        jTextField3.setText("0");
                        jTextField3.setMaximumSize(new java.awt.Dimension(40, 20));
                        jTextField3.setMinimumSize(new java.awt.Dimension(40, 20));
                        jTextField3.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jTextField3, "cell 3 3,alignx center,growy");
                jLabel2 = new javax.swing.JLabel();
                jLabel2.setForeground(new Color(0x05c986));
                jLabel2.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
                
                        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel2.setText("2");
                        jLabel2.setMaximumSize(new java.awt.Dimension(40, 20));
                        jLabel2.setMinimumSize(new java.awt.Dimension(40, 20));
                        jLabel2.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jLabel2, "cell 0 4,alignx center,growy");
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField4.setForeground(new Color(0x05c986));
        jTextField4.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField4.setText("0");
                jTextField4.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField4.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField4.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField4, "cell 1 4,alignx center,growy");
        jTextField5 = new javax.swing.JTextField();
        jTextField5.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField5.setForeground(new Color(0x05c986));
        jTextField5.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField5.setText("0");
                jTextField5.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField5.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField5.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField5, "cell 2 4,alignx center,growy");
                jTextField6 = new javax.swing.JTextField();
                jTextField6.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                jTextField6.setForeground(new Color(0x05c986));
                jTextField6.setBackground(SystemColor.inactiveCaptionText);
                
                        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                        jTextField6.setText("0");
                        jTextField6.setMaximumSize(new java.awt.Dimension(40, 20));
                        jTextField6.setMinimumSize(new java.awt.Dimension(40, 20));
                        jTextField6.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jTextField6, "cell 3 4,alignx center,growy");
                LoadBttn = new javax.swing.JButton();
                LoadBttn.setBackground(new Color(105, 105, 105));
                LoadBttn.setForeground(Color.WHITE);
                LoadBttn.setFont(new Font("Cambria", Font.BOLD, 12));
                LoadBttn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                
                        LoadBttn.setText("Load");
                        LoadBttn.addActionListener(new java.awt.event.ActionListener() 
                        {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LoadBttnActionPerformed(evt);
                            }
                        });
                        getContentPane().add(LoadBttn, "cell 5 4,alignx center,growy");
                jLabel3 = new javax.swing.JLabel();
                jLabel3.setForeground(new Color(0x05c986));
                jLabel3.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
                
                        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel3.setText("3");
                        jLabel3.setMaximumSize(new java.awt.Dimension(40, 20));
                        jLabel3.setMinimumSize(new java.awt.Dimension(40, 20));
                        jLabel3.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jLabel3, "cell 0 5,alignx center,growy");
                jTextField7 = new javax.swing.JTextField();
                jTextField7.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                jTextField7.setForeground(new Color(0x05c986));
                jTextField7.setBackground(SystemColor.inactiveCaptionText);
                
                        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                        jTextField7.setText("0");
                        jTextField7.setMaximumSize(new java.awt.Dimension(40, 20));
                        jTextField7.setMinimumSize(new java.awt.Dimension(40, 20));
                        jTextField7.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jTextField7, "cell 1 5,alignx center,growy");
                jTextField8 = new javax.swing.JTextField();
                jTextField8.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                jTextField8.setForeground(new Color(0x05c986));
                jTextField8.setBackground(SystemColor.inactiveCaptionText);
                
                        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                        jTextField8.setText("0");
                        jTextField8.setMaximumSize(new java.awt.Dimension(40, 20));
                        jTextField8.setMinimumSize(new java.awt.Dimension(40, 20));
                        jTextField8.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jTextField8, "cell 2 5,alignx center,growy");
        jTextField9 = new javax.swing.JTextField();
        jTextField9.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField9.setForeground(new Color(0x05c986));
        jTextField9.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField9.setText("0");
                jTextField9.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField9.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField9.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField9, "cell 3 5,alignx center,growy");
        DefaultBttn = new javax.swing.JButton();
        DefaultBttn.setBackground(new Color(105, 105, 105));
        DefaultBttn.setForeground(Color.WHITE);
        DefaultBttn.setFont(new Font("Cambria", Font.BOLD, 12));
        DefaultBttn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
                DefaultBttn.setText("Load default");
                DefaultBttn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        DefaultBttnActionPerformed(evt);
                    }
                });
                getContentPane().add(DefaultBttn, "cell 5 5,alignx center,aligny center");
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setForeground(new Color(0x05c986));
        jLabel4.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("4");
                jLabel4.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel4.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel4, "cell 0 6,alignx center,growy");
        jTextField10 = new javax.swing.JTextField();
        jTextField10.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField10.setForeground(new Color(0x05c986));
        jTextField10.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField10.setText("0");
                jTextField10.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField10.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField10.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField10, "cell 1 6,alignx center,growy");
        jTextField11 = new javax.swing.JTextField();
        jTextField11.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField11.setForeground(new Color(0x05c986));
        jTextField11.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField11.setText("0");
                jTextField11.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField11.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField11.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField11, "cell 2 6,alignx center,growy");
        jTextField12 = new javax.swing.JTextField();
        jTextField12.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField12.setForeground(new Color(0x05c986));
        jTextField12.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField12.setText("0");
                jTextField12.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField12.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField12.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField12, "cell 3 6,alignx center,growy");
                
          // data entered by the user
        
        btnImportFile = new JButton();
        btnImportFile.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importFile(evt);
            }
        });
        
       
        btnImportFile.setBackground(new Color(105, 105, 105));
        btnImportFile.setForeground(Color.WHITE);
        btnImportFile.setFont(new Font("Cambria", Font.BOLD, 12));
        btnImportFile.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnImportFile.setText("Import File");
        getContentPane().add(btnImportFile, "cell 5 6,alignx center");
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setForeground(new Color(0x05c986));
        jLabel5.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("5");
                jLabel5.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel5.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel5, "cell 0 7,alignx center,growy");
        jTextField13 = new javax.swing.JTextField();
        jTextField13.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField13.setForeground(new Color(0x05c986));
        jTextField13.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField13.setText("0");
                jTextField13.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField13.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField13.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField13, "cell 1 7,alignx center,growy");
        jTextField14 = new javax.swing.JTextField();
        jTextField14.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField14.setForeground(new Color(0x05c986));
        jTextField14.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField14.setText("0");
                jTextField14.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField14.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField14.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField14, "cell 2 7,alignx center,growy");
                jTextField15 = new javax.swing.JTextField();
                jTextField15.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
                jTextField15.setForeground(new Color(0x05c986));
                jTextField15.setBackground(SystemColor.inactiveCaptionText);
                
                        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                        jTextField15.setText("0");
                        jTextField15.setMaximumSize(new java.awt.Dimension(40, 20));
                        jTextField15.setMinimumSize(new java.awt.Dimension(40, 20));
                        jTextField15.setPreferredSize(new java.awt.Dimension(40, 20));
                        getContentPane().add(jTextField15, "cell 3 7,alignx center,growy");
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setForeground(new Color(0x05c986));
        jLabel6.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("6");
                jLabel6.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel6.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel6.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel6, "cell 0 8,alignx center,growy");
        jTextField16 = new javax.swing.JTextField();
        jTextField16.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField16.setForeground(new Color(0x05c986));
        jTextField16.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField16.setText("0");
                jTextField16.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField16.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField16.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField16, "cell 1 8,alignx center,growy");
        jTextField17 = new javax.swing.JTextField();
        jTextField17.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField17.setForeground(new Color(0x05c986));
        jTextField17.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField17.setText("0");
                jTextField17.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField17.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField17.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField17, "cell 2 8,alignx center,growy");
        jTextField18 = new javax.swing.JTextField();
        jTextField18.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField18.setForeground(new Color(0x05c986));
        jTextField18.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField18.setText("0");
                jTextField18.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField18.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField18.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField18, "cell 3 8,alignx center,growy");
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setForeground(new Color(0x05c986));
        jLabel7.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        
                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel7.setText("7");
                jLabel7.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel7.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel7.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel7, "cell 0 9,alignx center,growy");
        jTextField19 = new javax.swing.JTextField();
        jTextField19.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField19.setForeground(new Color(0x05c986));
        jTextField19.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField19.setText("0");
                jTextField19.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField19.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField19.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField19, "cell 1 9,alignx center,growy");
        jTextField20 = new javax.swing.JTextField();
        jTextField20.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField20.setForeground(new Color(0x05c986));
        jTextField20.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField20.setText("0");
                jTextField20.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField20.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField20.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField20, "cell 2 9,alignx center,growy");
        jTextField21 = new javax.swing.JTextField();
        jTextField21.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField21.setForeground(new Color(0x05c986));
        jTextField21.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField21.setText("0");
                jTextField21.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField21.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField21.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField21, "cell 3 9,alignx center,growy");
        
        lblNote = new JLabel("Note: If arrival, burst");
        lblNote.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        lblNote.setForeground(new Color(0x05c986));
        getContentPane().add(lblNote, "flowx,cell 5 9,alignx center,aligny center");
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setForeground(new Color(0x05c986));
        jLabel8.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("8");
                jLabel8.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel8.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel8.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel8, "cell 0 10,grow");
        jTextField22 = new javax.swing.JTextField();
        jTextField22.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField22.setForeground(new Color(0x05c986));
        jTextField22.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField22.setText("0");
                jTextField22.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField22.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField22.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField22, "cell 1 10,alignx center,growy");
        jTextField23 = new javax.swing.JTextField();
        jTextField23.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField23.setForeground(new Color(0x05c986));
        jTextField23.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField23.setText("0");
                jTextField23.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField23.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField23.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField23, "cell 2 10,alignx center,growy");
        jTextField24 = new javax.swing.JTextField();
        jTextField24.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField24.setForeground(new Color(0x05c986));
        jTextField24.setBackground(SystemColor.inactiveCaptionText);
        
                jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                jTextField24.setText("0");
                jTextField24.setMaximumSize(new java.awt.Dimension(40, 20));
                jTextField24.setMinimumSize(new java.awt.Dimension(40, 20));
                jTextField24.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jTextField24, "cell 3 10,alignx center,growy");
        
        lblAndPriorityIs = new JLabel("and priority is equal to zero, ");
        lblAndPriorityIs.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        lblAndPriorityIs.setForeground(new Color(0x05c986));
        getContentPane().add(lblAndPriorityIs, "cell 5 10,alignx center,aligny center");
        
        JLabel jLabel9 = new JLabel();
        jLabel9.setForeground(new Color(0x05c986));
        jLabel9.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        jLabel9.setText("9");
        jLabel9.setPreferredSize(new Dimension(40, 20));
        jLabel9.setMinimumSize(new Dimension(40, 20));
        jLabel9.setMaximumSize(new Dimension(40, 20));
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jLabel9, "cell 0 11,grow");
        
        jTextField25 = new JTextField();
        jTextField25.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField25.setForeground(new Color(0x05c986));
        jTextField25.setBackground(SystemColor.inactiveCaptionText);
        jTextField25.setText("0");
        jTextField25.setPreferredSize(new Dimension(40, 20));
        jTextField25.setMinimumSize(new Dimension(40, 20));
        jTextField25.setMaximumSize(new Dimension(40, 20));
        jTextField25.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jTextField25, "cell 1 11,alignx center,growy");
        
        jTextField26 = new JTextField();
        jTextField26.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField26.setForeground(new Color(0x05c986));
        jTextField26.setBackground(SystemColor.inactiveCaptionText);
        jTextField26.setText("0");
        jTextField26.setPreferredSize(new Dimension(40, 20));
        jTextField26.setMinimumSize(new Dimension(40, 20));
        jTextField26.setMaximumSize(new Dimension(40, 20));
        jTextField26.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jTextField26, "cell 2 11,alignx center,growy");
        
        jTextField27 = new JTextField();
        jTextField27.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField27.setForeground(new Color(0x05c986));
        jTextField27.setBackground(SystemColor.inactiveCaptionText);
        jTextField27.setText("0");
        jTextField27.setPreferredSize(new Dimension(40, 20));
        jTextField27.setMinimumSize(new Dimension(40, 20));
        jTextField27.setMaximumSize(new Dimension(40, 20));
        jTextField27.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jTextField27, "cell 3 11,alignx center,growy");
        
        lblItMeansNull = new JLabel("it means null job.");
        lblItMeansNull.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        lblItMeansNull.setForeground(new Color(0x05c986));
        getContentPane().add(lblItMeansNull, "cell 5 11,alignx center,aligny center");
        
        JLabel jLabel10 = new JLabel();
        jLabel10.setForeground(new Color(0x05c986));
        jLabel10.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        jLabel10.setText("10");
        jLabel10.setPreferredSize(new Dimension(40, 20));
        jLabel10.setMinimumSize(new Dimension(40, 20));
        jLabel10.setMaximumSize(new Dimension(40, 20));
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jLabel10, "cell 0 12,grow");
        
        jTextField28 = new JTextField();
        jTextField28.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField28.setForeground(new Color(0x05c986));
        jTextField28.setBackground(SystemColor.inactiveCaptionText);
        jTextField28.setText("0");
        jTextField28.setPreferredSize(new Dimension(40, 20));
        jTextField28.setMinimumSize(new Dimension(40, 20));
        jTextField28.setMaximumSize(new Dimension(40, 20));
        jTextField28.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jTextField28, "cell 1 12,alignx center,growy");
        
        jTextField29 = new JTextField();
        jTextField29.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField29.setForeground(new Color(0x05c986));
        jTextField29.setBackground(SystemColor.inactiveCaptionText);
        jTextField29.setText("0");
        jTextField29.setPreferredSize(new Dimension(40, 20));
        jTextField29.setMinimumSize(new Dimension(40, 20));
        jTextField29.setMaximumSize(new Dimension(40, 20));
        jTextField29.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jTextField29, "cell 2 12,alignx center,growy");
        
        jTextField30 = new JTextField();
        jTextField30.setBorder(new LineBorder(new Color(255, 218, 185), 1, true));
        jTextField30.setForeground(new Color(0x05c986));
        jTextField30.setBackground(SystemColor.inactiveCaptionText);
        jTextField30.setText("0");
        jTextField30.setPreferredSize(new Dimension(40, 20));
        jTextField30.setMinimumSize(new Dimension(40, 20));
        jTextField30.setMaximumSize(new Dimension(40, 20));
        jTextField30.setHorizontalAlignment(SwingConstants.CENTER);
        getContentPane().add(jTextField30, "cell 3 12,alignx center,growy");
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(new Color(0x05c986));
        jLabel1.setFont(new Font("Book Antiqua", Font.ITALIC, 12));
        jLabel1.setAlignmentX(0.5f);
        
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("1");
                jLabel1.setMaximumSize(new java.awt.Dimension(40, 20));
                jLabel1.setMinimumSize(new java.awt.Dimension(40, 20));
                jLabel1.setPreferredSize(new java.awt.Dimension(40, 20));
                getContentPane().add(jLabel1, "cell 0 3,alignx center,growy");

        pack();
    }// </editor-fold>                        

    
    @SuppressWarnings("deprecation")
	private void LoadBttnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        fillJobList();
        Face face = new Face();  // create new object of the main frame
        face.setAssignedQueue(new Queue(list));  // add list of jobs to the main queue
        face.show();
        this.dispose();
    }         
    
    private ArrayList<Job> list = new ArrayList<Job>(); // list of jobs entered by the user
    
 

   

	
    private void importFile(java.awt.event.ActionEvent evt) {
		
		// TODO Auto-generated method stub
    	JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
          File selectedFile = fileChooser.getSelectedFile();
       // System.out.println(selectedFile.getName());
	        try
	        {
	        	
	        	 int i=0;
	        	 
	        	Scanner x = new Scanner(selectedFile);
	        	
	        	
	    		 
	    		 while (x.hasNext())
	    	        {
	    	           importData[i*3] = x.next();
	    	           importData[(i*3)+1] = x.next();
	    	           importData[(i*3)+2] = x.next();
	    	         
	    	        //   System.out.printf("%s %s %s\n",importData[i*3],importData[(i*3)+1],importData[(i*3)+2]);
	    	        //   System.out.println(importData[(i*3)+1]);
	    	        //   System.out.println(importData[(i*3)+2]);
	    	           
	    	        jTextField1.setText(importData[0]);
	   	 	        jTextField2.setText(importData[1]);
	   	 	        jTextField3.setText(importData[2]);
	   	 	        jTextField4.setText(importData[3]);
	   	 	        jTextField5.setText(importData[4]);
	   	 	        jTextField6.setText(importData[5]);
	   	 	        jTextField7.setText(importData[6]);
	   	 	        jTextField8.setText(importData[7]);
	   	 	        jTextField9.setText(importData[8]);
	   	 	        jTextField10.setText(importData[9]);
	   	 	        jTextField11.setText(importData[10]);
	   	 	        jTextField12.setText(importData[11]);
	   	 	        jTextField13.setText(importData[12]);
	   	 	        jTextField14.setText(importData[13]);
	   	 	        jTextField15.setText(importData[14]);
	   	 	        jTextField16.setText(importData[15]);
	   	 	        jTextField17.setText(importData[16]);
	   	 	        jTextField18.setText(importData[17]);
	   	 	        jTextField19.setText(importData[18]);
	   	 	        jTextField20.setText(importData[19]);
	   	 	        jTextField21.setText(importData[20]);
	   	 	        jTextField22.setText(importData[21]);
	   	 	        jTextField23.setText(importData[22]); 
	   	 	        jTextField24.setText(importData[23]);
	   	 	        jTextField25.setText(importData[24]);
	   	 	        jTextField26.setText(importData[25]);
	   	 	        jTextField27.setText(importData[26]);
	   	 	        jTextField28.setText(importData[27]);
	   	 	        jTextField29.setText(importData[28]); 
	   	 	        jTextField30.setText(importData[29]); 
	    	           i++;
	    	           
	    	        }
	    		 x.close();
	    		 
	    		 
	    		
	    		 
	    		
	    			
	    		
	        }
	        catch(Exception e){
	        	JOptionPane.showMessageDialog(null,"error");
	        }
        }
		
        
		
	}

	
	
			// TODO Auto-generated method stub
		

	/**
     * load default data for all the jobs
     * @param evt 
     */
    private void DefaultBttnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        jTextField1.setText("0");
        jTextField2.setText("1");
        jTextField3.setText("21");
        jTextField4.setText("24");
        jTextField5.setText("3");
        jTextField6.setText("39");
        jTextField7.setText("15");
        jTextField8.setText("12");
        jTextField9.setText("85");
        jTextField10.setText("1");
        jTextField11.setText("2");
        jTextField12.setText("3");
        jTextField13.setText("12");
        jTextField14.setText("8");
        jTextField15.setText("84");
        jTextField16.setText("26");
        jTextField17.setText("11");
        jTextField18.setText("49");
        jTextField19.setText("16");
        jTextField20.setText("7");
        jTextField21.setText("69");
        jTextField22.setText("11");
        jTextField23.setText("8");
        jTextField24.setText("16");  
        jTextField25.setText("22");
        jTextField26.setText("9");
        jTextField27.setText("67");
        jTextField28.setText("18");
        jTextField29.setText("6");
        jTextField30.setText("17");  
    }                                           
     
  //  private ArrayList<Job> list = new ArrayList<Job>(); // list of jobs entered by the user
    protected int [] userData = new int [30];  // data entered by the user
    protected int fillJobList()
    {
        getData(); // collect data from the frame
        for(int i=0 ; i<9 ; i++)
        {
            int arriveTime = userData[i*3];
            int burstTime = userData[(i*3)+1];
            int priority = userData[(i*3)+2];
            if(checkJob(arriveTime,burstTime,priority ))
            {
               list.add(new Job(i+1, arriveTime, burstTime, priority));
            }
        }
        return 0;
    }
    
    /**
     * fillJobList that the entered data are within limits.
     * limits are set by try and error according to the GUI limits
     * @param arrive arrive time of the job
     * @param burst burst time of the job
     * @param priority priority of the job
     * @return true if data are within limits
     */
    private boolean checkJob(int arrive , int burst , int priority)
    {
        if( arrive < 0  || arrive > 30 ) {return false;}
        if( burst <= 0 || burst > 13 ) {return false;}
        if( priority <=0  || priority > 127) {return false;}
        return true;
    }
       
    /**
     * get the data from the frame and put it in an array
     */
    private void getData ()
    {
        try {
        userData[0] = Integer.parseInt(jTextField1.getText());
        userData[1] = Integer.parseInt(jTextField2.getText());
        userData[2] = Integer.parseInt(jTextField3.getText());
        userData[3] = Integer.parseInt(jTextField4.getText());
        userData[4] = Integer.parseInt(jTextField5.getText());
        userData[5] = Integer.parseInt(jTextField6.getText());
        userData[6] = Integer.parseInt(jTextField7.getText());
        userData[7] = Integer.parseInt(jTextField8.getText());
        userData[8] = Integer.parseInt(jTextField9.getText());
        userData[9] = Integer.parseInt(jTextField10.getText());
        userData[10] = Integer.parseInt(jTextField11.getText());
        userData[11] = Integer.parseInt(jTextField12.getText());
        userData[12] = Integer.parseInt(jTextField13.getText());
        userData[13] = Integer.parseInt(jTextField14.getText());
        userData[14] = Integer.parseInt(jTextField15.getText());
        userData[15] = Integer.parseInt(jTextField16.getText());
        userData[16] = Integer.parseInt(jTextField17.getText());
        userData[17] = Integer.parseInt(jTextField18.getText());
        userData[18] = Integer.parseInt(jTextField19.getText());
        userData[19] = Integer.parseInt(jTextField20.getText());
        userData[20] = Integer.parseInt(jTextField21.getText());
        userData[21] = Integer.parseInt(jTextField22.getText());
        userData[22] = Integer.parseInt(jTextField23.getText());
        userData[23] = Integer.parseInt(jTextField24.getText()); 
        userData[24] = Integer.parseInt(jTextField25.getText());
        userData[25] = Integer.parseInt(jTextField26.getText());
        userData[26] = Integer.parseInt(jTextField27.getText());
        userData[27] = Integer.parseInt(jTextField28.getText());
        userData[28] = Integer.parseInt(jTextField29.getText());
        userData[29] = Integer.parseInt(jTextField30.getText()); 
        }
        catch (Exception e)  // insufficeint input will trigger an error message
        { }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddData().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton DefaultBttn;
    private javax.swing.JButton LoadBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private JTextField jTextField25;
    private JTextField jTextField26;
    private JTextField jTextField27;
    private JTextField jTextField28;
    private JTextField jTextField29;
    private JTextField jTextField30;
    private JButton btnImportFile;
    private JLabel lblTo;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
    private JLabel lblNote;
    private JLabel lblAndPriorityIs;
    private JLabel lblItMeansNull;
    private JLabel lblPriority;
    private String [] importData = new String [30];
}
